CREATE TABLE comments (
	id SERIAL PRIMARY KEY,
	created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
	user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	argument_id INTEGER NOT NULL REFERENCES arguments(id) ON DELETE CASCADE,
	body VARCHAR(1000) NOT NULL
);

